//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int facilityId { get; set; }
        public Nullable<System.TimeSpan> startDateTime { get; set; }
        public Nullable<System.TimeSpan> endDateTime { get; set; }
        public Nullable<double> cost { get; set; }
        public string notes { get; set; }
        public Nullable<bool> cancelled { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual User User { get; set; }
    }
}
