//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityTime
    {
        public int Id { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Facility Facility { get; set; }
    }
}
