//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int facilityId { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> comment { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual User User { get; set; }
    }
}
