//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBook.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> IsReadFlag { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
    
        public virtual User User { get; set; }
    }
}
